repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      - id: ruff-check # linter
        args: [--fix]
      - id: ruff-check
        name: ruff sort imports
        args: [--select, I, --fix]
      - id: ruff-format # formatter

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.0
    hooks:
    - id: bandit
      files: ^src/

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.11.1
    hooks:
    - id: pyproject-fmt

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
    - id: validate-pyproject
      name: validate pyproject.toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        additional_dependencies:
          - alembic
          - pydantic
          - pydantic-settings
          - sqlalchemy
